In [1]:
import numpy as np
import matplotlib.pylab as plt

In [2]:
m_list_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [3]:
np_m_arr_1 = np.array(m_list_1)

In [4]:
np_m_arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np_m_arr_1.shape

(3, 3)

In [6]:
np_m_arr_1[0,1]

2

In [7]:
np_m_arr_1.item(0,1)

2

In [8]:
np.take(np_m_arr_1, [0, 3, 6])

array([1, 4, 7])

In [9]:
np.put(np_m_arr_1, [0, 3, 6], [10, 10, 10])

In [10]:
np_m_arr_1

array([[10,  2,  3],
       [10,  5,  6],
       [10,  8,  9]])

In [14]:
list_1 = [1, 2, 3, 4, 5]

In [15]:
np_arr_1 = np.array(list_1, dtype=np.int8)

In [16]:
np_arr_1

array([1, 2, 3, 4, 5], dtype=int8)

In [17]:
np_arr_1[:5:2]

array([1, 3, 5], dtype=int8)

In [18]:
np_m_arr_1[:,1]

array([2, 5, 8])

In [19]:
np_arr_1[::-1]

array([5, 4, 3, 2, 1], dtype=int8)

In [20]:
evens = np_m_arr_1[np_m_arr_1%2==0]

In [21]:
evens 

array([10,  2, 10,  6, 10,  8])

In [22]:
np_m_arr_1[np_m_arr_1 > 5]

array([10, 10,  6, 10,  8,  9])

In [23]:
np_m_arr_1[(np_m_arr_1 > 5) & (np_m_arr_1 < 9)]

array([6, 8])

In [24]:
np_m_arr_1[(np_m_arr_1 > 5) | (np_m_arr_1 == 10)]

array([10, 10,  6, 10,  8,  9])

In [25]:
np.unique(np_m_arr_1)

array([ 2,  3,  5,  6,  8,  9, 10])